//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AB.ThingsILike.BO
{
    using System;
    using System.Collections.Generic;
    
    
    [Serializable]
    public partial class ListItem
    {
        public int li_id { get; set; }
        public int li_l_id { get; set; }
        public string li_name { get; set; }
        public int li_order { get; set; }
    
        public virtual List List { get; set; }
    }
}
