//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AB.ThingsILike.BO
{
    using System;
    using System.Collections.Generic;
    
    
    [Serializable]
    public partial class List
    {
        public List()
        {
            this.ListItems = new HashSet<ListItem>();
        }
    
        public int l_id { get; set; }
        public int l_user_id { get; set; }
        public string l_name { get; set; }
    
        public virtual ICollection<ListItem> ListItems { get; set; }
        public virtual User User { get; set; }
    }
}
