//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AB.ThingsILike.BO
{
    using System;
    using System.Collections.Generic;
    
    
    [Serializable]
    public partial class User
    {
        public User()
        {
            this.Lists = new HashSet<List>();
        }
    
        public int u_id { get; set; }
        public string u_username { get; set; }
    
        public virtual ICollection<List> Lists { get; set; }
    }
}
